### PR TITLE
Update MacOS and Linux to 2.4.8 and add Apple Silicon support

### LINKED ISSUE #6: macOS and Linux Plugins are not up-to-date
It seems like the macOS x86-x64/libenet.bundle and the Linux x86-x64/libenet.so were not updated when updating to 2.4.8.
On MacOs I get this error:

```
InvalidOperationException: Incompatatible version
ENet.Library.Initialize () (at Assets/ENet/Scripts/ENet.cs:959)
Netcode.Transports.Enet.EnetTransport.Initialize (Unity.Netcode.NetworkManager networkManager) (at Assets/ENet/EnetTransport.cs:304)
Unity.Netcode.NetworkManager.Initialize (System.Boolean server) (at Library/PackageCache/com.unity.netcode.gameobjects@1.0.0-pre.7/Runtime/Core/NetworkManager.cs:778)
Unity.Netcode.NetworkManager.StartHost () (at Library/PackageCache/com.unity.netcode.gameobjects@1.0.0-pre.7/Runtime/Core/NetworkManager.cs:866)
ApplicationSettings.StartHost (TrackerType trackingSercviceType) (at Assets/MxRP/Scripts/ApplicationManagement/ApplicationSettings.cs:353)
ApplicationSettings.OnDataloadingComplete () (at Assets/MxRP/Scripts/ApplicationManagement/ApplicationSettings.cs:242)
MxrpPortal+<InitializeLoadingAsync>d__5.MoveNext () (at Assets/MxRP/Scripts/ApplicationManagement/MxrpPortal.cs:91)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
MxrpPortal+<Start>d__4.MoveNext () (at Assets/MxRP/Scripts/ApplicationManagement/MxrpPortal.cs:65)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

### PR DESCRIPTION
**Pull request by elhodel**
I added the missing Libraries (Mac and Linux) that didn't got updated to Version 2.4.8 as well as Apple Silicon support.

The Release should be updated with an up-to-date .unitypackage after merging this pull request i guess.

Closes #6

### CODE REVIEW

**Comment by JohannesDeml** [comment]
Thanks a lot for the PR, this is highly appreciated! I just tried running the branch on an MacBook Pro 2021 with an M1 Pro, and sadly I get an exception:
```
DllNotFoundException: enet assembly:<unknown assembly> type:<unknown type> member:(null)
ENet.Library.Initialize () (at Assets/ENet/Scripts/ENet.cs:956)
Supyrb.ENetClient..ctor () (at Assets/Runtime/ENetClient.cs:62)
Supyrb.ExampleEchoClient.Start () (at Assets/Samples/EchoClient/Scripts/ExampleEchoClient.cs:39)
```
Screenshot 2022-10-09 at 17 08 52

Did you test the library on your machine with the repo?

Small note aside: I tried running it with 2021.3.11f1, but I guess this should not be a problem.

**Comment by elhodel** [comment]
no i did not test with your project 😄, i don't have a m1 mac... but a coworker had enet running on m1 with the library i pushed. (not your project tho...)
do the import settings look correct?

**Comment by JohannesDeml** [comment]
Screenshot 2022-10-09 at 17 42 42

Yep, I would say, they look fine.
I also tried to compile it on my machine, sadly I didn't manage to get it to run in Unity either (but I'm also not super familiar with the process).

**Comment by JohannesDeml** [comment]
Okay, I managed to get a working version for both MacOS x64 and ARM. I will still merge this, since the linux fix is in there and I want to give credit where credit is due. thanks ffor your contribution!

**Pull request merged**
